export const COMPANY = {
  name: 'Lumina Labs',
  plan: 'EOR + Contractors + Payroll',
  admin: { name: 'Priya Shah', role: 'Head of People' },
  deadline: '21 Sep 2026',
  daysLeft: 30,
  assumption:
    'Prototype for an interview case study. Company, workers, and the Brazil 30-day conversion are fictional. Product shape follows public Oyster capabilities (EOR, contractors, payroll) plus a proposed unified conversion layer.',
}

export const COLORS = [
  '#0F3E4D', '#1E4637', '#412850', '#16485a', '#4B1937', '#2a6b4e', '#3d8eab', '#7a4e2a',
]

export function initials(name) {
  return name.split(' ').map((p) => p[0]).slice(0, 2).join('')
}

export function colorFor(name) {
  let n = 0
  for (const c of name) n += c.charCodeAt(0)
  return COLORS[n % COLORS.length]
}

export const COUNTRIES = [
  { name: 'United States', eor: 8, contractor: 2, payroll: 6, total: 16 },
  { name: 'Brazil', eor: 2, contractor: 10, payroll: 0, total: 12 },
  { name: 'United Kingdom', eor: 6, contractor: 1, payroll: 3, total: 10 },
  { name: 'Germany', eor: 5, contractor: 0, payroll: 2, total: 7 },
  { name: 'India', eor: 4, contractor: 3, payroll: 0, total: 7 },
  { name: 'Portugal', eor: 4, contractor: 1, payroll: 0, total: 5 },
  { name: 'Canada', eor: 3, contractor: 0, payroll: 1, total: 4 },
  { name: 'Poland', eor: 3, contractor: 0, payroll: 0, total: 3 },
  { name: 'Mexico', eor: 2, contractor: 1, payroll: 0, total: 3 },
  { name: 'Spain', eor: 2, contractor: 0, payroll: 0, total: 2 },
  { name: 'Netherlands', eor: 2, contractor: 0, payroll: 0, total: 2 },
  { name: 'Philippines', eor: 1, contractor: 0, payroll: 0, total: 1 },
]

export const BRAZIL_CONTRACTORS = [
  {
    id: 'br-01',
    name: 'Ana Oliveira',
    role: 'Senior Software Engineer',
    city: 'São Paulo',
    manager: 'Noah Kim',
    start: '12 Mar 2024',
    invoice: 18000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 92,
    status: 'at_risk',
    cltBase: 12500,
    employerCost: 21840,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'PIS', 'bank'],
    note: 'Exclusive, uses Lumina GitHub + Slack, reports to US engineering manager.',
  },
  {
    id: 'br-02',
    name: 'Bruno Santos',
    role: 'Product Designer',
    city: 'Rio de Janeiro',
    manager: 'Maya Chen',
    start: '3 Jun 2024',
    invoice: 14000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 88,
    status: 'at_risk',
    cltBase: 9800,
    employerCost: 17150,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF'],
    note: 'Standups daily. Design system owned inside Lumina Figma org.',
  },
  {
    id: 'br-03',
    name: 'Camila Ferreira',
    role: 'Data Analyst',
    city: 'Belo Horizonte',
    manager: 'Noah Kim',
    start: '18 Nov 2023',
    invoice: 12000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 90,
    status: 'at_risk',
    cltBase: 8400,
    employerCost: 14700,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'bank'],
    note: 'Warehouse access via Lumina SSO. No other clients declared.',
  },
  {
    id: 'br-04',
    name: 'Diego Costa',
    role: 'Backend Engineer',
    city: 'Curitiba',
    manager: 'Noah Kim',
    start: '9 Jan 2025',
    invoice: 16000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 86,
    status: 'at_risk',
    cltBase: 11200,
    employerCost: 19600,
    oysterFeeUsd: 699,
    block: 'ip',
    docs: ['RG', 'CPF'],
    note: 'Prior IP assignment sits in a PJ contract with a third-party studio. Legal must novate.',
  },
  {
    id: 'br-05',
    name: 'Elena Rocha',
    role: 'Customer Success Lead',
    city: 'São Paulo',
    manager: 'Priya Shah',
    start: '22 Apr 2024',
    invoice: 13000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 84,
    status: 'at_risk',
    cltBase: 9100,
    employerCost: 15925,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'PIS', 'bank'],
    note: 'Manages named accounts. Customer-facing title already used on Lumina website.',
  },
  {
    id: 'br-06',
    name: 'Felipe Almeida',
    role: 'Mobile Engineer',
    city: 'Recife',
    manager: 'Noah Kim',
    start: '1 Aug 2024',
    invoice: 15000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 87,
    status: 'at_risk',
    cltBase: 10500,
    employerCost: 18375,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF'],
    note: 'App Store credentials issued by Lumina. On-call rotation.',
  },
  {
    id: 'br-07',
    name: 'Gabriela Lima',
    role: 'Marketing Manager',
    city: 'Brasília',
    manager: 'Maya Chen',
    start: '14 Feb 2025',
    invoice: 11000,
    currency: 'BRL',
    hours: 32,
    exclusive: false,
    tools: true,
    risk: 71,
    status: 'at_risk',
    cltBase: 7700,
    employerCost: 13475,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'bank'],
    note: '32h/week. One other small client. Still flagged under pejotização guidance because of brand representation.',
  },
  {
    id: 'br-08',
    name: 'Henrique Souza',
    role: 'QA Engineer',
    city: 'Porto Alegre',
    manager: 'Noah Kim',
    start: '5 May 2024',
    invoice: 10000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 85,
    status: 'at_risk',
    cltBase: 7000,
    employerCost: 12250,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'PIS'],
    note: 'Embedded in sprint ceremonies. Device farm paid by Lumina.',
  },
  {
    id: 'br-09',
    name: 'Isabela Martins',
    role: 'Finance Operations',
    city: 'São Paulo',
    manager: 'Priya Shah',
    start: '30 Sep 2023',
    invoice: 12500,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 89,
    status: 'at_risk',
    cltBase: 8750,
    employerCost: 15312,
    oysterFeeUsd: 699,
    block: null,
    docs: ['RG', 'CPF', 'PIS', 'bank'],
    note: 'Approves vendor invoices. High PE-risk if left as PJ.',
  },
  {
    id: 'br-10',
    name: 'João Pereira',
    role: 'DevOps Engineer',
    city: 'Florianópolis',
    manager: 'Noah Kim',
    start: '11 Dec 2024',
    invoice: 17000,
    currency: 'BRL',
    hours: 40,
    exclusive: true,
    tools: true,
    risk: 91,
    status: 'at_risk',
    cltBase: 11900,
    employerCost: 20825,
    oysterFeeUsd: 699,
    block: 'docs',
    docs: ['RG'],
    note: 'Production admin. CPF on file stale. Country Expert must re-verify identity before CLT contract.',
  },
]

export const OTHER_PEOPLE = [
  { id: 'us-01', name: 'Noah Kim', role: 'VP Engineering', country: 'United States', city: 'Austin', type: 'payroll', status: 'active', start: '2 Feb 2021' },
  { id: 'uk-01', name: 'Amelia Ward', role: 'Staff Engineer', country: 'United Kingdom', city: 'London', type: 'eor', status: 'active', start: '8 Jul 2023' },
  { id: 'de-01', name: 'Lars Becker', role: 'Solutions Engineer', country: 'Germany', city: 'Berlin', type: 'eor', status: 'active', start: '19 Jan 2024' },
  { id: 'in-01', name: 'Arjun Mehta', role: 'Frontend Engineer', country: 'India', city: 'Bengaluru', type: 'contractor', status: 'active', start: '4 Mar 2025' },
  { id: 'pt-01', name: 'Sofia Almeida', role: 'People Partner', country: 'Portugal', city: 'Lisbon', type: 'eor', status: 'active', start: '16 Aug 2023' },
  { id: 'ca-01', name: 'Jordan Lee', role: 'Account Executive', country: 'Canada', city: 'Toronto', type: 'eor', status: 'active', start: '21 Oct 2024' },
  { id: 'pl-01', name: 'Kasia Nowak', role: 'Data Engineer', country: 'Poland', city: 'Warsaw', type: 'eor', status: 'onboarding', start: '1 Sep 2026' },
  { id: 'mx-01', name: 'Luis Herrera', role: 'Support Engineer', country: 'Mexico', city: 'CDMX', type: 'contractor', status: 'active', start: '12 May 2025' },
  { id: 'br-11', name: 'Marina Costa', role: 'Country Expert (internal)', country: 'Brazil', city: 'São Paulo', type: 'eor', status: 'active', start: '—', internal: true },
  { id: 'uk-02', name: 'Tom Hughes', role: 'Controller', country: 'United Kingdom', city: 'Manchester', type: 'payroll', status: 'active', start: '3 Apr 2022' },
  { id: 'us-02', name: 'Maya Chen', role: 'VP Product', country: 'United States', city: 'New York', type: 'payroll', status: 'active', start: '11 Nov 2020' },
  { id: 'es-01', name: 'Inés Ruiz', role: 'Recruiter', country: 'Spain', city: 'Madrid', type: 'eor', status: 'active', start: '7 Jan 2025' },
]

export function allPeople() {
  const brazil = BRAZIL_CONTRACTORS.map((p) => ({
    ...p,
    country: 'Brazil',
    type: p.status === 'converted' ? 'eor' : 'contractor',
    displayStatus: p.status,
  }))
  return [...brazil, ...OTHER_PEOPLE.filter((p) => !p.internal)]
}

export const PAYROLL_RUNS = [
  { id: 'pr-1', cycle: 'August 2026 — EOR', date: '31 Aug 2026', people: 42, amount: '$412,880', status: 'funded', exceptions: 1 },
  { id: 'pr-2', cycle: 'August 2026 — Payroll (own entity)', date: '31 Aug 2026', people: 12, amount: '$186,420', status: 'in_review', exceptions: 0 },
  { id: 'pr-3', cycle: 'August 2026 — Contractors', date: '5 Sep 2026', people: 18, amount: '$74,210', status: 'scheduled', exceptions: 2 },
  { id: 'pr-4', cycle: 'September 2026 — EOR (incl. Brazil CLT)', date: '30 Sep 2026', people: 52, amount: '$498,100', status: 'draft', exceptions: 0 },
]

export const INVOICES = [
  { id: 'INV-2041', type: 'EOR pre-funding', due: '24 Aug 2026', amount: '$398,210', status: 'paid' },
  { id: 'INV-2048', type: 'Contractor payouts', due: '5 Sep 2026', amount: '$74,210', status: 'open' },
  { id: 'INV-2052', type: 'EOR security deposit (Brazil 10)', due: '4 Sep 2026', amount: '$38,640', status: 'pending_conversion' },
]

export const OPS_TICKETS = [
  {
    id: 'OPS-441',
    team: 'Legal',
    owner: 'Priya N. (Oyster Legal)',
    worker: 'Diego Costa',
    title: 'Novate IP from third-party PJ studio',
    sla: '5 days',
    context: 'Conversion BR-04. Existing IP clause with Studio Norte. CLT contract blocked until assignment is novated to Oyster as EOR then licensed to Lumina.',
    need: 'Lumina legal sign-off on novation letter. Worker signature.',
  },
  {
    id: 'OPS-442',
    team: 'Country Expert',
    owner: 'Marina Costa',
    worker: 'João Pereira',
    title: 'Re-verify CPF and PIS before CLT',
    sla: '3 days',
    context: 'Conversion BR-10. CPF checksum failed overnight scan. Production admin — do not convert on stale identity.',
    need: 'Worker uploads new RG + CPF. Marina confirms against Receita Federal.',
  },
  {
    id: 'OPS-443',
    team: 'Support',
    owner: 'Alex Rivera',
    worker: 'Gabriela Lima',
    title: 'Worker asked: keep 32h and second client?',
    sla: '2 days',
    context: 'BR-07. Misclassification score 71. Possible part-time CLT. Country Expert recommended 32h CLT + written second-client disclosure.',
    need: 'Priya Shah (Lumina) confirms hours. Then regenerate contract.',
  },
]

export const WIZARD_STEPS = [
  { id: 0, title: 'Scope', sub: 'Who must convert, and why' },
  { id: 1, title: 'Classify', sub: 'Misclassification analyser' },
  { id: 2, title: 'Compensation', sub: 'PJ invoice → CLT package' },
  { id: 3, title: 'Exceptions', sub: 'Legal & country expert' },
  { id: 4, title: 'Contracts', sub: 'Generate CLT agreements' },
  { id: 5, title: 'Worker consent', sub: 'Docs, e-sign, questions' },
  { id: 6, title: 'Payroll lock', sub: 'First EOR cycle' },
  { id: 7, title: 'Launch', sub: 'Go live inside 30 days' },
]

export const HIRE_STEPS = [
  { id: 0, title: 'Country', sub: 'Where they will work' },
  { id: 1, title: 'Candidate', sub: 'Who you are hiring' },
  { id: 2, title: 'Local terms', sub: 'What employment means here' },
  { id: 3, title: 'Compensation', sub: 'Salary and true cost' },
  { id: 4, title: 'Setup', sub: 'Docs, deposit, invite' },
  { id: 5, title: 'Sent', sub: 'They are in People' },
]

export const COUNTRY_GUIDES = {
  Brazil: {
    entityOnFile: false,
    employmentName: 'CLT via Oyster EOR',
    legalEmployer: 'Oyster (local entity)',
    timeToHire: '5–10 days after docs (48h possible once KYC clears)',
    probation: '90 days (45 + 45)',
    notice: '30 days',
    vacation: '30 days + 1/3 constitutional bonus',
    thirteenth: '13th salary (mandatory)',
    statutory: ['INSS employer ~20%', 'FGTS 8%', '13th salary', 'Vacation + 1/3', 'eSocial registration'],
    docs: ['RG or CNH', 'CPF', 'PIS / NIT', 'Proof of address', 'Bank or PIX', 'Digital CTPS'],
    benefits: [
      { name: 'Local health (Oyster Brazil pack)', included: true },
      { name: 'Meal voucher (VR)', included: true, amount: 800 },
      { name: 'Transport voucher (VT)', included: true, amount: 220 },
      { name: 'Life insurance', included: true },
    ],
    costMultiple: 1.75,
    currency: 'BRL',
    defaultBase: 14000,
    defaultCity: 'São Paulo',
    expert: 'Marina Costa',
    crackdown: 'Pejotização enforcement: exclusive 40h engineering work must be CLT, not PJ.',
    feeEor: 699,
    feePayroll: null,
  },
  'United Kingdom': {
    entityOnFile: true,
    employmentName: 'UK employment · Lumina entity',
    legalEmployer: 'Lumina Labs UK Ltd',
    timeToHire: '3–5 days',
    probation: '3 months',
    notice: '1 month',
    vacation: '28 days including bank holidays',
    thirteenth: 'None',
    statutory: ['PAYE', 'Employer NI', 'Workplace pension'],
    docs: ['Passport / right to work', 'NI number', 'P45 or new-starter checklist', 'Bank'],
    benefits: [
      { name: 'Private medical', included: true },
      { name: 'Pension (auto-enrol)', included: true },
    ],
    costMultiple: 1.28,
    currency: 'GBP',
    defaultBase: 72000,
    defaultCity: 'London',
    expert: 'Amelia Ward (People)',
    crackdown: null,
    feeEor: 699,
    feePayroll: 109,
  },
  'United States': {
    entityOnFile: true,
    employmentName: 'US employment · Lumina entity',
    legalEmployer: 'Lumina Labs Inc',
    timeToHire: '2–4 days',
    probation: 'At-will · 90-day intro',
    notice: 'At-will',
    vacation: 'Unlimited PTO policy on file',
    thirteenth: 'None',
    statutory: ['FICA', 'FUTA', 'State unemployment', 'Workers comp'],
    docs: ['I-9', 'W-4', 'Direct deposit', 'State tax form'],
    benefits: [
      { name: 'Medical / dental / vision', included: true },
      { name: '401(k)', included: true },
    ],
    costMultiple: 1.32,
    currency: 'USD',
    defaultBase: 145000,
    defaultCity: 'Austin',
    expert: 'US payroll ops',
    crackdown: null,
    feeEor: 699,
    feePayroll: 109,
  },
  Germany: {
    entityOnFile: false,
    employmentName: 'German employment via Oyster EOR',
    legalEmployer: 'Oyster (local entity)',
    timeToHire: '7–12 days',
    probation: '6 months',
    notice: '4 weeks to month-end (statutory)',
    vacation: '24+ statutory · 30 common',
    thirteenth: 'Often 13th / Christmas bonus by custom',
    statutory: ['Social security', 'Health insurance', 'Pension', 'Unemployment'],
    docs: ['Passport', 'Tax ID', 'Social security number', 'Bank IBAN'],
    benefits: [
      { name: 'Statutory health', included: true },
      { name: 'BahnCard / mobility', included: false },
    ],
    costMultiple: 1.22,
    currency: 'EUR',
    defaultBase: 78000,
    defaultCity: 'Berlin',
    expert: 'Lars Becker (Solutions)',
    crackdown: null,
    feeEor: 699,
    feePayroll: 109,
  },
  India: {
    entityOnFile: false,
    employmentName: 'Indian employment via Oyster EOR',
    legalEmployer: 'Oyster (local entity)',
    timeToHire: '5–8 days',
    probation: '3–6 months',
    notice: '30–90 days by band',
    vacation: 'Earned leave + casual + sick (state rules)',
    thirteenth: 'None (bonus discretionary)',
    statutory: ['PF', 'ESI if eligible', 'Gratuity', 'Professional tax'],
    docs: ['PAN', 'Aadhaar', 'Bank', 'Address proof'],
    benefits: [
      { name: 'Mediclaim', included: true },
      { name: 'PF', included: true },
    ],
    costMultiple: 1.18,
    currency: 'INR',
    defaultBase: 2800000,
    defaultCity: 'Bengaluru',
    expert: 'India country expert',
    crackdown: 'Misclassification analyser still runs. Exclusive product work should not sit on a contractor SOW.',
    feeEor: 699,
    feePayroll: 109,
  },
  Portugal: {
    entityOnFile: false,
    employmentName: 'Portuguese employment via Oyster EOR',
    legalEmployer: 'Oyster (local entity)',
    timeToHire: '6–10 days',
    probation: '90–240 days by role',
    notice: '15–75 days by tenure',
    vacation: '22 days',
    thirteenth: 'Holiday + Christmas subsidies (14th)',
    statutory: ['Social security 23.75%', 'Work accident insurance', '14th salary'],
    docs: ['NIF', 'NISS', 'IBAN', 'Address', 'ID'],
    benefits: [
      { name: 'Health (Médis-style pack)', included: true },
      { name: 'Meal card', included: true, amount: 7.63 },
    ],
    costMultiple: 1.35,
    currency: 'EUR',
    defaultBase: 52000,
    defaultCity: 'Lisbon',
    expert: 'Sofia Almeida',
    crackdown: null,
    feeEor: 699,
    feePayroll: 109,
  },
}

export const DISCOVERY = [
  { who: 'Customer (Priya)', what: 'Shadow current contractor → EOR path. Count handoffs, tools, emails.' },
  { who: 'Workers (3 of 10)', what: 'Interview: take-home fear, second clients, trust in CLT vs PJ.' },
  { who: 'Country Expert BR', what: 'Map pejotização triggers, FGTS/INSS, 13th, vacation, union.' },
  { who: 'Legal + Support', what: 'Ticket archaeology: where conversions stall, what context is missing.' },
  { who: 'Finance', what: 'True cost of conversion vs termination vs entity setup. Deposit impact.' },
  { who: 'Data', what: 'Time-in-stage, reopen rate, payroll exceptions after first EOR cycle.' },
]
